### ISSUE TITLE
Spatio-Temporal timeseries prediction

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/TimeseriesPrediction.jl#16]
In principle spatio-temporal timeseries prediction should already be possible by providing the Reconstruction.

Once JuliaDynamics/DynamicalSystemsBase.jl#47 is implemented,
a dedicated interface for this could be offered.

The call signature could look like this
`localmodel_tsp(s,D,τ,I,K,c, p ; kwargs)`

**Comment by Datseris** [comment]
I think this is too advanced to be offered as a standard feature.

**Comment by Datseris** [comment]
dONE in #19
