### ISSUE TITLE
Change all source code of `data[range, 1:2]` 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#3]
# Issue Description
Change all source code of `data[range, 1:2]`  to 
```
sind = SVector(1, 2)
data[range, sind]
```

The latter is 100x faster.

**Comment by Datseris** [comment]
lol I have written it wrong when I first posted. I have updated now.

**Comment by JonasIsensee** [comment]
Nothing to be done. This function is not used in the package but only in tests for multivariate timeseries prediction
