### ISSUE TITLE
Light Cone constructor for SpatioTemporalEmbedding

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/TimeseriesPrediction.jl#34]
Implement a constructor for `SpatioTemporalEmbedding` that
creates a light cone like embedding.
Likely needs just one parameter. Speed

Note: `STE` implements a forward embedding. 

- [ ] Example for the docs

**Comment by JonasIsensee** [comment]
`function indices_within(radius, dimension)
    #Return indices β within hypersphere with radius
    #Floor radius to nearest integer. Does not lose points
    r = floor(Int,radius)
    #Hypercube of indices
    hypercube = CartesianIndices((repeat([-r:r], dimension)...,))
    #Select subset of hc which is in Hypersphere

    βs = [ β for β ∈ hypercube if norm(β.I) <= radius ]
end


function TimeseriesPrediction.SpatioTemporalEmbedding(
    s::AbstractArray{<:AbstractArray{T,Φ}}, ΔT, τ, speed, boundary::BC
    ) where {T,Φ, BC<:AbstractBoundaryCondition}
    if !(BC <: PeriodicBoundary) && typeof(boundary.c) != T
        throw(ArgumentError(
        "Boundary value must be same element type as the timeseries data."))
    end

    τs = Int[]
    βs = CartesianIndex{Φ}[]
    for delay = ΔT:-τ:1 # Backwards for forward embedding 1:τ:ΔT
        radius = max(speed*delay, 1.) # No radius lower than 1
        β = indices_within(radius, Φ)
        push!(βs, β...)
        push!(τs, repeat([ΔT - delay], length(β))...)
    end
    X = length(τs)
    return SpatioTemporalEmbedding{X}(τs, βs, boundary, size(s[1]))
end



function visualize_STE(em::STE{2}, τ)
    points = [ β.I for (delay,β) in zip(em.τ,em.β) if delay == τ]
    x = map(xy -> xy[1], points)
    y = map(xy -> xy[2], points)
    r = maximum(x)

    figure()
    grid()
    axis("equal")
    xticks(-r:r)
    yticks(-r:r)
    scatter(x,y, color="black", s=100)
    scatter([0],[0], color="red", s=100)
end

s = [rand(10,10) for i =1:5];
em = SpatioTemporalEmbedding(s, 5,1,1,PeriodicBoundary())

visualize_STE(em, 4)
visualize_STE(em, 3)
visualize_STE(em, 2)
visualize_STE(em, 1)
visualize_STE(em, 0)
`

**Comment by JonasIsensee** [comment]
@Datseris : This Constructor is quite simple.
I think we could also just add it into the library on top of highlighting it as as example in the docs.

**Comment by JonasIsensee** [comment]
![example_cone](https://user-images.githubusercontent.com/33990604/45756572-7d7bad00-bc21-11e8-855d-de4656efe37a.png)
Example with ΔT = 1, τ = 1 and speed =1

**Comment by Datseris** [comment]
What did you do about the fact that this implements forward embedding?

**Comment by JonasIsensee** [comment]
Not sure what your comment means.
To clarify:
AFAICT `DynamicalSystemsBase.jl` implements a forward embedding such as
```math
x_t = (s_t, s_{t+\tau}, \dots, s_{t+D\tau})
```
or in the new implementation with
```math
x_t = (s_t, s_{t+\tau_1}, \dots, s_{t+\tau_D})
```
with all τ > 0 and the largest τ referring the most recent measurement.

The same is true for `TimeseriesPrediction.jl`: Only positive `τ` that are used as `s[t+τ]` (instead of `s[t-τ]` which could also be done)

This is important for this type of embedding. If I do it the wrong way around, we end up with a cone that expands in the wrong direction of time.
