### ISSUE TITLE
Logo for TimeseriesPrediction.jl

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#43]
We want a cool logo. Let's discuss this here.

**Comment by Datseris** [comment]
Update: @JonasIsensee has made one, it is displayed in the webpage of Julia dynamics. it should be added to the homepage of the documentation as well though.

**Comment by JonasIsensee** [comment]
@Datseris 
You seem to have figured out how to add the logo to a repo inside some kind of _blob_.
After that, including it at the top of the readme seems easy enough.

**Comment by Datseris** [comment]
Hi @JonasIsensee , sorry I don't get what the question is. You wanna know how to include it in the README, in the built documentation using MkDocs, or in the JuliaDynamics website? Each one is using a different syntax unfortunately...

**Comment by Datseris** [comment]
Actually I'll do this, sorry that I forgot. It will only take me a couple of minutes tomorrow.
