### ISSUE TITLE
Improve spatio temporal prediction tests

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#44]
1. They never tests cross predictions of periodic models
2. They must test the field values themselves, besides a coarse grained average of a prediction.
3. They should test both maximum and minimum errors

**Comment by JonasIsensee** [comment]
1. If you wish, but it will need to be a quick test. Tests take long enough already...

2. I do not understand 

3. I do not see the point for maximum errors.
I have seen lots of these predictions and average errors are predictable.
Only for very long training sets ( not possible on travis )  the maximum errors go down a little bit and a test
`@test 0 < predicted_value < maximum(field)` does not seem particularly useful

**Comment by JonasIsensee** [comment]
ok. Fair enough.
The scale of barkley is pretty close to 0-1 anyway. So I will just add `minimum(abs_err) < 0.1`.
