### ISSUE TITLE
In systems_def.jl allow parameters to be arguments instead of hardcoded

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#45]
In short, make this:
```
function barkley_periodic_boundary(T, Nx, Ny)
    a = 0.75
    b = 0.02
    ε = 0.02
```
this:
```
function barkley_periodic_boundary(T, Nx, Ny;  a = 0.75, b = 0.02, ε = 0.02)
```

**Comment by JonasIsensee** [comment]
If we're going to work on these, we should add the diffusion constant `D` as well.
That is needed for the chaotic behaviour.

Maybe make `periodic::Bool` an argument? 
That removes the need for maintaining a separate Barkley function.

**Comment by Datseris** [comment]
> Maybe make `periodic::Bool` an argument?
> That removes the need for maintaining a separate Barkley function.

Yeah very nice idea.

The old versions do not have `D` in them, so I'll leave this one to you...

**Comment by JonasIsensee** [comment]
Working on it.
