### ISSUE TITLE
Parameter `c` used twice

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/TimeseriesPrediction.jl#49]
Not sure if this is a big problem but nonetheless:
We use `c` as name for `ConstantBoundary` parameter
and `c` as _speed_ in `light_cone_embedding_.

**Comment by Datseris** [comment]
bugs. bugs everywhere. push it on master :D

**Comment by Datseris** [comment]
@JonasIsensee where is this? In documentation string? I can't find it.

**Comment by Datseris** [comment]
Bump, is this still valid @JonasIsensee ?

**Comment by JonasIsensee** [comment]
This still exists but I don't find it to be particularly relevant.
The relevant code is this
```
"""
	ConstantBoundary(c) <: AbstractBoundaryCondition
Constant boundary condition type. Enforces constant boundary conditions
when passed to [`SpatioTemporalEmbedding`](@ref)
by filling missing out-of-bounds values in the reconstruction with
parameter `c`.
"""
struct ConstantBoundary{T} <: AbstractBoundaryCondition
    c::T
end
```

(and the light-speed parameter `c` , of course )

**Comment by Datseris** [comment]
the field of `ConstantBoundary` is not exposed in the High Level API. We can just change the documentation string and be done with it! You can put e.g. `x` instead of `c`.

**Comment by JonasIsensee** [comment]
lower case `b` for boundary?

**Comment by Datseris** [comment]
yeah this is also fine. I think it is sufficiently different from `β`
