### ISSUE TITLE
make theiler window argument of `predict_timeseries`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#5]
From `predict_timeseries`:

```julia
    for n=1:p   #Iteratively estimate timeseries
        idxs,dists = neighborhood_and_distances(q,R, tree,ntype)
        xnn = R[idxs]
        ynn = R[idxs+step]
        q = method(q, xnn, ynn, dists)
        push!(s_pred, q[end])
    end
```
clearly the theiler window is not used in `neighborhood_and_distances(q,R, tree,ntype)`

The theiler window should be **keyword argument** of the `predict_timeseries` and be normally used as expected.

You can make `w = mean(τ)` for the call without `R`, and `w = mean(R.delay)` for the call with `R`.

**Comment by JonasIsensee** [comment]
As far as I can tell, the current implementation of theiler windows does not work here.
The theiler neighborhoods require an index n for the query, which does not exist in general.

Instead we would need a method that makes sure the nearest neighbors are not temporal neighbors of eachother....

**Comment by Datseris** [comment]
> The theiler neighborhoods require an index n for the query, which does not exist in general.

Damn, you are right.

**Comment by Datseris** [comment]
Well, on the other hand, you can still find the closest neighbor and then not allow temporal neighbors of the closest neighbor. See here: https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/45

**Comment by JonasIsensee** [comment]
What do you think of this?
could something like this work?

```julia
function neighborhood_and_distances(point::AbstractVector,R::AbstractDataset, tree,
                      ntype::FixedMassNeighborhood; w::Int = 1)
    ind = Int[]
    function f(i)
        for j ∈ ind
            if abs(i-j) < w
                return true
            end
        end
        push!(ind,i)
        return false
    end
    idxs,dists = knn(tree, point, ntype.K, false, f)
    return idxs,dists
end
```

**Comment by Datseris** [comment]
Nice approach. Seems like it would work, but may have performance issues. 

If it is bad, you can increase the performance by making `f` a Functor instead, with the only field a `Vector{Int}`, I guess...

**Comment by Datseris** [comment]
@JonasIsensee I think this is a nice approach. We should have it in `DynamicalSystemsBase` `neighborhood` as well.

**Comment by Datseris** [comment]
@JonasIsensee the theiler window is currently not an argument of `localmodel_tsp`. Make it a keyword argument that defaults to `mean(τ)` for methods that have τ and to `mean(R.delay)` for methods that given an abstract dataset.

**Comment by JonasIsensee** [comment]
Which implementation of it do you want though?

**Comment by Datseris** [comment]
The one we have already. That excludes temporal neighbors of the query point only.

The only thing that is left is to only have the argument to `tsp` a swell.

**Comment by JonasIsensee** [comment]
> > The theiler neighborhoods require an index n for the query, which does not exist in general.

> Damn, you are right.

**Comment by Datseris** [comment]
my brain is literally out of order.
