### ISSUE TITLE
2Dfield_crossprediction.jl example does not work anymore...?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#59]
@JonasIsensee do you know porque? When I run it I get error on the line
`pcaem = PCAEmbedding(source_train, em; maxoutdim=5) `

**Comment by JonasIsensee** [comment]
I don't know yet. But my first investigations suggests
that this is due to some changes in `MultivariateStats.jl`.

The stacktrace shows the error occurring there.
