### ISSUE TITLE
Make `localmodel_tsp` return the `B` end of a reconstruction only

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#7]
When given a `Reconstruction` or a `MDReconstruction`, make it so that it automatically returns the last column, or the last `B` columns.

To make the source code clear, we keep the lower level method with abstract dataset as is, and rename it to `_localmodel_tsp` (with one `_` in front). Then the methods that take a `Reconstruction` or `MDReconstruction` call this function and return only the last `B` columns.

If you have this `::MDReconstruction{DxB, D, B, T, τ}` then you know you can create the
`a = SVector{B, Int}((DxB - i for i in B-1:-1:0)...)` and simple return the returned result as `ret[:, a]`.

(When given a timeseries, or `Dataset` the behavior should remain as it is now)

**Comment by Datseris** [comment]
@JonasIsensee I am assinging you because I think this one will be a good practice for improving multiple dispatch understanding and skills.

**Comment by JonasIsensee** [comment]
I believe I did that. Please review the Pull Request.

**Comment by Datseris** [comment]
This can be made much easier simply by using returning always the same dimension as `s`, and when passing `(s, D, τ)` to first do a reconstruction (still return same dimensions as  `s`)

**Comment by JonasIsensee** [comment]
I'm not exactly sure what you're suggesting but I did shorten things a bit. 
Given a timeseries (`AbstractVector` or `AbstractDataset`) it performs a delay embedding and then calls the next `localmodel_tsp` method that takes in a prepared `Reconstruction`. I feel like it looks cleaner now, and especially more code is being reused now.

**Comment by JonasIsensee** [comment]
I got it down to three methods....

But now a given `Reconstruction` or `MDReconstruction` is treated as an `AbstractDataset` and everything is returned!

Only when a (multivariate) timeseries is given, it does the fancy stuff and returnes the last `B` columns.

Is this what you want?

**Comment by Datseris** [comment]
Closed in #9
