### ISSUE TITLE
Documentation: light_cone_embedding and r0

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesPrediction.jl#71]
The documentation of `light_cone_embedding` does not have `r0` anymore (for no reason whatsoever).

But this creates a problem as it states:

> The radius of the light cone evolves as: `r = i*τ*c + r` for each step `i ∈ 0:γ`.

while the two `r` symbols used in the equation actually mean different things.

**Comment by JonasIsensee** [comment]
The "no reason whatsoever" is the paper that has been submitted for publication.
Renaming `r\_0` to `r` was one of the few things Ulrich cared about.
It adds unnecessary complexity. [.. in the naming scheme ]
We could amend the docs to say

`r_i = i*τ*c + r` for each step `i ∈0:γ`

**Comment by Datseris** [comment]
Yeah this is okay.
