### ISSUE TITLE
Compile fail : AbstractDataset not defined

### ISSUE THREAD

**Issue by chene-vert** [JuliaDynamics/TimeseriesPrediction.jl#93]
When adding TimeseriesPrediction  to a projet the compilation fails.
(using add TimeseriesPrediction from REPL)

```
Precompiling project...
  ✗ TimeseriesPrediction
  0 dependencies successfully precompiled in 17 seconds (99 already precompiled)

ERROR: The following 1 direct dependency failed to precompile:

TimeseriesPrediction [f218859d-9706-56aa-9ebf-1fa4ed7b8020]

ERROR: LoadError: LoadError: UndefVarError: AbstractDataset not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/TimeseriesPrediction/kyJEr/src/localmodeling.jl:241
 [2] include(x::String)
   @ TimeseriesPrediction ~/.julia/packages/TimeseriesPrediction/kyJEr/src/TimeseriesPrediction.jl:4
 [3] top-level scope
   @ ~/.julia/packages/TimeseriesPrediction/kyJEr/src/TimeseriesPrediction.jl:11
 [4] top-level scope (repeats 2 times)
   @ none:1
```

But when cloning the source (HEAD), the repository can be precompiled successfully. 
add TimeseriesPrediction.jl.git#master  works... 

This is probably due to the fact that TimeseriesPrediction is added locked to the last version known : V0.6.0.

 * commit e483148b20d54cb3e9d36749c034c55f1a27364a (HEAD -> master, origin/master, origin/HEAD)
   Date:   Mon Apr 6 20:52:01 2020 +0200

 * commit 7e40b78d5670b7051c92fab48a054d83a204d8e5 (tag: v0.6.0)
   Date:   Wed Oct 31 17:43:49 2018 +0100

**Comment by JonasIsensee** [comment]
Hi @chene-vert ,
thanks for pointing this out.
I updated the compat section of the `Project.toml` in #94 and will tag a new release shortly

**Comment by chene-vert** [comment]
👍

Thanks for sharing your work!
